services:
  holesail-sidecar:
    container_name: holesail-sidecar
    build: .
    ports:
      - 5150:8787
    #restart: unless-stopped
    #volumes:
    #  - /data/docker/holesail-testing/data:/root/.pm2
    environment:
      MODE: server # defaults to client
      PUBLIC: true #defaults to false
      PORT: 25565
      HOST: meinkraft
      CONNECTOR: null #NPgMky1ztMYGArnNGvROb5UQPnUpGPKPMeOPLfFuxBVPVwhAwK3d19qFMV4rmEfBMoaMeaRKM5Uyzpeu47dH7T77TYp1XxqmnkUwAUkyIWrpMuuAbrH
      ROLE: user
      USERNAME: bob
      PASSWORD: bob
      FORCE: false
      RANDOM_ORG_API_KEY: ${RANDOM_ORG_API_KEY}
    # networks:
    # - coolify
    #labels:
    #  - traefik.enable=true
    #  - traefik.http.middlewares.gzip.compress=true
    #  - traefik.http.routers.holesail-sidecar.rule=Host(`mc.daedalist.net`) &&
    #    PathPrefix(`/`)
    #  - traefik.http.routers.holesail-sidecar.entrypoints=http
    #  - traefik.http.routers.holesail-sidecar.service=holesail-sidecar
    #  - traefik.http.routers.holesail-sidecar.middlewares=gzip
    #  - traefik.http.services.holesail-sidecar.loadbalancer.server.port=8787
# networks:
#   coolify:
#     external: true
